# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ky7vboln2_aJqx_RI8Ddm-HnNM9nGYf
"""

import pandas as pd
import networkx as nx
import json
import ast
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import pprint
import numpy as np
import time
import datetime

df = pd.read_csv("listings.csv")

df2 = pd.read_csv("calendar.csv")

df.head(2)

loc = df[["id", "listing_url", "name", "description", "neighborhood_overview", "host_id", "host_name", "neighbourhood_cleansed","latitude","longitude","property_type","accommodates", "bathrooms_text","bedrooms","beds","amenities","price", "minimum_nights","maximum_nights","number_of_reviews","review_scores_rating"]]

loc.to_json('listings.json', orient='records')

list(loc.columns)

loc.dtypes

loc['price'] = loc['price'].replace('[\$\,\.]', '', regex=True).astype(int)

loc.head(2)

df2.head(3)

df2.rename(columns={"listing_id":"id"}, inplace = True);

df2['date'] = df2['date'].astype(str)

df2 = df2.drop(df2[df2.date == 'nan'].index);

result = []
for i in df2["date"]:
  result.append(time.mktime(datetime.datetime.strptime(str(i), "%Y-%m-%d").timetuple())) 

df2['ts'] = result



df2['ts'].min()

df2['ts'].max()

df2.to_csv('calendar_ts.csv', index=False)

df3 = pd.read_csv("calendar_ts.csv")

df3.head(31)

df3['date'] = df3['date'].astype(str)

df3.dtypes

time.mktime(datetime.datetime.strptime("2022-12-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-11-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-10-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-09-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-08-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-07-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-06-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-05-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-04-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-03-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-02-01", "%Y-%m-%d").timetuple())

time.mktime(datetime.datetime.strptime("2022-01-01", "%Y-%m-%d").timetuple())

df3.to_json("calendar.json")

dfc = pd.read_csv("calendar_ts.csv")

dfc.head(3)

dfc.to_json('calendar_ts.json', orient='records')

dfc['price'] = dfc['price'].replace('[\$\,\.]', '', regex=True).astype(int)

